### ISSUE TITLE
Umbrella issue for ML Workflows on OpenShift content

### ISSUE THREAD

**Issue by willb** [AICoE/learn-katacoda#11]
It would be nice to have the content from the [https://github.com/willb/openshift-ml-workflows-workshop](ML workflows workshop) available in Katacoda.  Individual scenarios will link back to this issue.

**Comment by willb** [comment]
(cc @sophwats)

**Comment by 4n4nd** [comment]
@willb maybe you could start with adding a Dockerfile to your repo that builds a jupyter notebook image just like [this](https://github.com/hemajv/prometheus-anomaly-detection-workshop/blob/a9c7beeefe2668cb9017dcdda57c62ee8ce4fcc7/Dockerfile-pac). Since we are using your template, it should be very similar.
